2020-06-26T15:02:02|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "KeithleyApp.py", line 24, in <module>
    app = KeithleyTestApp(sys.argv)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "KeithleyApp.py", line 10, in setup
    self.hw = self.add_hardware(KeithleySourceMeterComponent(self))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 80, in __init__
    self.setup()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 40, in setup
    self.source_V_a_range = self.settings.New('source_V_a_range', float, choices = self.v_ranges.keys())
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 1106, in New
    lq = LoggedQuantity(name=name, dtype=dtype, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 90, in __init__
    self.choices = self._expand_choices(choices)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 146, in _expand_choices
    expanded_choices.append( ( str(c), self.dtype(c) ) )
ValueError: could not convert string to float: '210 mV'

