2020-07-02T14:28:50|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "KeithleyApp.py", line 28, in <module>
    app = KeithleyTestApp(sys.argv)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "KeithleyApp.py", line 12, in setup
    self.k24002 = self.add_hardware(Keithley2400SourceMeterComponent(self))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 605, in add_hardware
    assert not hw.name in self.hardware.keys()
AssertionError

