2020-06-25T10:00:57|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 78, in <lambda>
    self.source_V_a_range.connect_to_hardware(lambda:self.read_range('SOUR', 'VOLT'),
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 119, in read_range
    _range = self.keithley.read_range(sour_or_sens, v_or_i)
NameError: name 'v_or_i' is not defined

2020-06-25T10:01:46|ERROR|KeithleyTestApp|tried to disconnect keithley_sourcemeter: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
