2020-06-19T15:02:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 61, in connect
    K = self.keithley = KeithleySourceMeter(port=self.port.val, debug=self.debug_mode.val)
NameError: name 'KeithleySourceMeter' is not defined

