2020-06-24T17:22:25|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "KeithleyApp.py", line 31, in <module>
    app = KeithleyTestApp(sys.argv)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "KeithleyApp.py", line 13, in setup
    self.hw.settings['port'] = 'GPIB0::22'
AttributeError: 'KeithleyTestApp' object has no attribute 'hw'

