2020-06-22T15:51:59|WARNING|pymeasure.adapters.vxi11|Failed to import vxi11 package, which is required for the VXI11Adapter
2020-06-22T15:52:21|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in connect
    self.V_a.connect_to_hardware(K.read_V())
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 613, in query
    return self.read()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 427, in read
    message = self._read_raw().decode(enco)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 400, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 107, in disconnect
    self.keithley.close()
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 46, in close
    self.keithley.shutdown()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\keithley\keithley2400.py", line 693, in shutdown
    if self.source_mode == 'current':
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 148, in fget
    vals = self.values(get_command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:52:21|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in connect
    self.V_a.connect_to_hardware(K.read_V())
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 613, in query
    return self.read()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 427, in read
    message = self._read_raw().decode(enco)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 400, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

