2020-06-23T10:46:49|WARNING|pymeasure.adapters.vxi11|Failed to import vxi11 package, which is required for the VXI11Adapter
2020-06-23T10:47:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 162, in read_from_hardware
    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 220, in update_value
    new_val = self.sender().text()
AttributeError: 'NoneType' object has no attribute 'text'

2020-06-23T10:48:43|ERROR|KeithleyTestApp|tried to disconnect keithley_sourcemeter: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
