2020-06-24T17:00:40|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 63, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 102, in read_V
    resp = self.ask(":READ?")
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 33, in ask
    resp = self.keithley.read()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 427, in read
    message = self._read_raw().decode(enco)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 400, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-24T17:04:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 103, in disconnect
    self.keithley.write_output_on(False)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 93, in write_output_on
    self.send(s)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 40, in send
    self.keithley.write(cmd)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

