2020-06-23T15:18:21|WARNING|pymeasure.adapters.vxi11|Failed to import vxi11 package, which is required for the VXI11Adapter
2020-06-23T15:18:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 100, in read_NPLC
    return self.keithley.current_nplc
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 148, in fget
    vals = self.values(get_command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-23T15:23:59|ERROR|KeithleyTestApp|tried to disconnect keithley_sourcemeter: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
