2020-06-18T17:00:41|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "KeithleyApp.py", line 21, in <module>
    app = KeithleyTestApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "KeithleyApp.py", line 9, in setup
    from keithley_sourcemeter.keithley_sourcemeter_hc import KeithleySourceMeterComponent
ModuleNotFoundError: No module named 'keithley_sourcemeter'

