2020-06-22T15:10:19|WARNING|pymeasure.adapters.vxi11|Failed to import vxi11 package, which is required for the VXI11Adapter
2020-06-22T15:10:36|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 61, in connect
    K = self.keithley = KeithleySourceMeter(port=self.port.val, debug=self.debug_mode.val)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 29, in __init__
    self.keithley.reset_buffer()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\keithley\buffer.py", line 105, in reset_buffer
    self.write(":STAT:PRES;*CLS;:TRAC:CLEAR;:TRAC:FEED:CONT NEXT;")
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 99, in write
    self.adapter.write(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 86, in write
    self.connection.write(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_NLISTENERS (-1073807265): No listeners condition is detected (both NRFD and NDAC are deasserted).

2020-06-22T15:10:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 613, in query
    return self.read()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 427, in read
    message = self._read_raw().decode(enco)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 400, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:11:01|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:11:11|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:11:21|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:11:31|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:11:41|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 64, in <lambda>
    self.V_a.connect_to_hardware(lambda:K.read_V(),None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 134, in read_V
    return self.keithley.voltage
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 607, in query
    self.write(message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-22T15:15:57|ERROR|KeithleyTestApp|tried to disconnect keithley_sourcemeter: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
