2020-06-26T17:04:33|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 88, in <lambda>
    lambda delay:K.write_source_delay(delay))
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 182, in write_source_delay
    self.send(':SOUR:DEL? %g' % (delay))
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 46, in send
    self.keithley.write(cmd)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-26T17:04:36|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 88, in <lambda>
    lambda delay:K.write_source_delay(delay))
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 181, in write_source_delay
    self.send(":SOUR:DEL:AUTO False")
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 46, in send
    self.keithley.write(cmd)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 228, in write
    count = self.write_raw(message.encode(enco))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\resources\messagebased.py", line 202, in write_raw
    return self.visalib.write(self.session, message)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1866, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

2020-06-26T17:05:22|ERROR|KeithleyTestApp|tried to disconnect keithley_sourcemeter: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
